try {
  console.log(`i`, i);
} catch (error) {
  console.log(`Erreur attrapée : `, error);
}
/* console.error(`Erreur attrapée : `, error); */